### ISSUE TITLE
not same with main theme.

### ISSUE THREAD

**Issue by b1ack0p** [fagnerpc/ARTFLIX-NX-Recalbox#1]
it doesnt look like main ARTFLIX theme for Batocera. a bit different.
settings menu is too dark and small.
is it possible to make it compatible for CRT screens? and put option to make things a bit bigger - especially menu titles - texts etc?
thanks.

**Comment by fagnerpc** [comment]
It doesn't look like the main ARTFLIX theme for Batocera because it's a different theme. The default theme is at this link: https://github.com/fagnerpc/Alekfull-ARTFLIX-Recalbox.

I have no way of testing it on CRT's... so, at the moment I don't have a way to make this theme compatible with CRT's
